# Generated by Django 3.2.9 on 2022-02-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_profile_pics/default.jpg', null=True, upload_to='user_profile_pics'),
        ),
    ]
