# Generated by Django 3.2.9 on 2022-02-23 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_img', models.ImageField(default='business_profile_pics/salon.jpeg', upload_to='business_profile_pics')),
                ('b_name', models.CharField(max_length=50)),
                ('b_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('b_contact', models.BigIntegerField(unique=True)),
                ('b_address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpDept',
            fields=[
                ('dept_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(choices=[('Hair', 'Hair'), ('Skin', 'Skin'), ('Nails', 'Nails'), ('Tattoo', 'Tattoo')], max_length=50)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serv_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serv_name', models.CharField(max_length=150)),
                ('serv_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Child(below 12 years)', 'Child(below 12 years)'), ('Others', 'Others')], default='Male', max_length=50)),
                ('serv_desc', models.TextField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('emp_contact', models.BigIntegerField(unique=True)),
                ('role', models.CharField(max_length=50)),
                ('emp_dob', models.DateField()),
                ('emp_doj', models.DateField()),
                ('emp_salary', models.FloatField()),
                ('dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curl_admin.empdept')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('cust_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('cust_contact', models.BigIntegerField(unique=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curl_admin.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='employee',
            field=models.ManyToManyField(to='curl_admin.Employee'),
        ),
        migrations.AddField(
            model_name='business',
            name='services',
            field=models.ManyToManyField(to='curl_admin.Services'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='curl_admin.customer')),
                ('services', models.ManyToManyField(to='curl_admin.Services')),
                ('staff', models.ManyToManyField(null=True, related_name='employee', to='curl_admin.Employee')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
