# Generated by Django 3.2.9 on 2022-02-24 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curl_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curl_admin.customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ManyToManyField(related_name='employee', to='curl_admin.Employee'),
        ),
    ]
