# Generated by Django 3.2.9 on 2022-02-24 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curl_admin', '0003_auto_20220224_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ucustomer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ucustomer', to=settings.AUTH_USER_MODEL),
        ),
    ]
