# Generated by Django 3.2.9 on 2022-02-24 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curl_admin', '0005_alter_appointment_ucustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ucustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ucustomer', to=settings.AUTH_USER_MODEL),
        ),
    ]
