# Generated by Django 3.2.9 on 2022-02-24 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curl_admin', '0006_alter_appointment_ucustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdept',
            name='user',
        ),
        migrations.AddField(
            model_name='empdept',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
