# Generated by Django 3.2.9 on 2022-02-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curl_admin', '0008_alter_services_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshours',
            name='business',
        ),
        migrations.AddField(
            model_name='business',
            name='b_hours',
            field=models.ManyToManyField(to='curl_admin.BusinessHours'),
        ),
    ]
