# Generated by Django 3.2.9 on 2022-02-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curl_admin', '0010_auto_20220226_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='emp_profile_pics/employee.png', null=True, upload_to='emp_profile_pics'),
        ),
    ]
